name = str(input("Enter your answer : "))
given_name = str(input("Enter your answer : "))
additional_name = str(input("Enter your answer : "))
family_name = str(input("Enter your answer : "))
nick_name = str(input("Enter your answer : "))
birthday= (input("Enter your answer : "))
note = (input("Enter your answer : "))
group_membership = (input("Enter your answer : "))
email = (input("Enter your answer : "))
phone = (input("Enter your answer : "))

with open('information.csv','w') as fileOut:
    fileOut.write('Name,')
    fileOut.write('Given Name,')
    fileOut.write('Additional Name,')
    fileOut.write('Family Name,')
    fileOut.write('Nickname,')
    fileOut.write('Birthday,')
    fileOut.write('Notes,')
    fileOut.write('Group Membership,')
    fileOut.write('E-mail 1 - Value,')
    fileOut.write('Phone 1 - Value\n')

    fileOut.write(name + ',')
    fileOut.write(given_name+ ',')
    fileOut.write(additional_name+ ',')
    fileOut.write(family_name+ ',')
    fileOut.write(nick_name+ ',')
    fileOut.write(birthday+ ',')
    fileOut.write(note+ ',')
    fileOut.write(group_membership+ ',')
    fileOut.write(email+ ',')
    fileOut.write(phone+ ',')